Logs:Logs: 


Booting up...
Time: 2023-12-08 09:32:41
Python version: 3.8.12 (default, Aug 30 2021, 16:42:10) 
[GCC 10.3.0]
System version: sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)
Discord.py version: 2.1.1
Running on: linux
/home/runner/Bot2/venv/bin/python

[2023-12-08 09:32:41] [INFO    ] discord.client: logging in using static token
[2023-12-08 09:32:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f55acb908511ced8d5fc2a1d5dca05a6).
✅ Modot#0831
✅ Synced 6 commands.

[2023-12-08 09:33:00] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'embedded-text-builder'
Traceback (most recent call last):
  File "/home/runner/Bot2/venv/lib/python3.8/site-packages/discord/app_commands/commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "main.py", line 202, in embedded_text
    message = await interaction.response.send_message(embed=embedded_text_modal.message.embeds[0], components=[embedded_text_modal])
AttributeError: 'EmbeddedTextModal' object has no attribute 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/Bot2/venv/lib/python3.8/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/runner/Bot2/venv/lib/python3.8/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/runner/Bot2/venv/lib/python3.8/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'embedded-text-builder' raised an exception: AttributeError: 'EmbeddedTextModal' object has no attribute 'message'
